streamnative/terraform-provider-pulsar

- README.md
- go.sum
- pulsar/resource_pulsar_namespace.go
- types/types.go
I added two namespace configuration options for setting up schema validation enforce and schema compatibility strategy.
Any comments are welcome :)
> Feat: Add schema options to namespace

- .github/workflows/release.yaml
- .goreleaser.yml
Following terraform provider's [release guideline](https://www.terraform.io/docs/registry/providers/publishing.html#github-actions-preferred-) for github actions
> Add release action

- .github/workflows/acctest.yaml
- Makefile
- README.md
- hack/pulsar-docker.sh
- hack/pulsarimage/Dockerfile
- hack/pulsarimage/entrypoint.sh
- pulsar/resource_pulsar_topic.go
- pulsar/resource_pulsar_topic_test.go
Signed-off-by: Zixuan Liu <nodeces@gmail.com>
> feat: add retention policies for topic level

- pulsar/resource_pulsar_namespace.go
Signed-off-by: Zixuan Liu <nodeces@gmail.com>
Fix #43
> fix: add schema compatibility strategy and validation enforcer to namespace config

- examples/clusters/main.tf
- examples/namespaces/main.tf
- examples/tenants/main.tf
Fixes #42 
The example includes error syntax.
Change versions to `version`
*(or)*
*(or)*
*(example:)*
Need to update docs? 
(If you need help on updating docs, create a doc issue)
(Please explain why)
(If this PR contains doc changes)
> Fix version in examples

- .github/workflows/acctest.yaml
- .github/workflows/documentbot.yml
- .github/workflows/linter.yml
- .github/workflows/release.yaml
- .goreleaser.yml
- terraform-registry-manifest.json
Master Issue: #18 
Fix CI for release
Updated the versions of actions and remove unused steps.
*(or)*
*(or)*
*(example:)*
Need to update docs? 
(If you need help on updating docs, create a doc issue)
(Please explain why)
(If this PR contains doc changes)
> Fix CI for release

- go.mod
- go.sum
- pulsar/provider_test.go
- pulsar/resource_pulsar_sink_test.go
- pulsar/resource_pulsar_source_test.go
Fix the following error:
```
pulsar_topic.sample-topic-1: Creating...
pulsar_topic.sample-topic-2: Creating...
pulsar_topic.sample-topic-1: Creation complete after 2s [id=persistent://public/default/partition-topic]
╷
│ Error: ERROR_CREATE_TOPIC: code: 400 reason: Cannot deserialize value of type `java.util.LinkedHashMap<java.lang.String,java.lang.String>` from Integer value (token `JsonToken.VALUE_NUMBER_INT`)
│  at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 1]
│ 
│   with pulsar_topic.sample-topic-2,
│   on main.tf line 22, in resource "pulsar_topic" "sample-topic-2":
│   22: resource "pulsar_topic" "sample-topic-2" {
│ 
╵
```
Correct log:
```
pulsar_topic.sample-topic-1: Creating...
pulsar_topic.sample-topic-2: …
```
> Upgrade pulsarctl and fix test

- README.md
- docs/index.md
- pkg/admin/admin.go
- pkg/admin/admin_config.go
- pkg/authentication/type.go
- pulsar/provider.go
Fixes #60 
Support authentication using OAuth2
```hcl
provider "pulsar" {
web_service_url = "https://***.test.aws.sn2.dev"
issuer_url = "https://***..dev"
client_id = "VNCbYg1G37x4AK***"
audience = "urn:sn:***"
key_file_path = "file:///admin.json"
}
```
docs have been updated in this PR.
> Support OAuth2 authentication

- README.md
Update docs
Update docs.
*(or)*
*(or)*
*(example:)*
Need to update docs? 
(If you need help on updating docs, create a doc issue)
(Please explain why)
(If this PR contains doc changes)
> [Docs] Use command `make build-dev` to build binary in local environment

- README.md
- examples/clusters/main.tf
- examples/namespaces/main.tf
- examples/sinks/main.tf
- examples/sources/main.tf
- examples/tenants/main.tf
- examples/topics/main.tf
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
> fix examples in tenants

- go.mod
- go.sum
- pulsar/resource_pulsar_sink.go
- pulsar/resource_pulsar_source.go
Fixes #94
1. TF cannot work with pulsar package URL `source://` `sink://` "function://"
2. builtin connectors are not handled correctly
*(or)*
*(or)*
*(example:)*
- *Extended integration test for recovery after …
> fix source/sink connector archive/packageURL support

- .github/workflows/acctest.yaml
We need to check pulsar logs when the acctest failed in CI.
Like this one: https://github.com/streamnative/terraform-provider-pulsar/actions/runs/5649027967/job/15333868396?pr=97
add tmate session for acctest debug
> ci: add tmate session for acctest debug

- README.md
- examples/sinks/main.tf
- examples/sources/main.tf
- hack/pulsarimage/Dockerfile
- hack/pulsarimage/entrypoint.sh
- pulsar/resource_pulsar_sink_test.go
- pulsar/resource_pulsar_source_test.go
- pulsar/testdata/sink/main.tf
- pulsar/testdata/source/main.tf
Fixes #<xyz>
`2.8.1` was released two years ago which is too old for testing.
*(or)*
*(or)*
*(example:)*
Need to update docs? 
(If …
> upgrade pulsar to 2.10.4 for test

- README.md
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
> docs: add version compatibility

- README.md
- examples/functions/main.tf
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
> add function example and doc

- .github/workflows/release.yaml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
> fix(ci): gpg key in the release action

- pulsar/resource_pulsar_function.go
- pulsar/resource_pulsar_sink.go
Fixes #<xyz>
Make Pulsar Functions & Sink Connector's input topics / subscription name forcenew to prevent the value cannot be altered error
*(or)*
*(or)*
*(example:)*
- *Extended integration test for recovery after …
> make input topics and subscription forcenew

- .github/workflows/linter.yml
- .goreleaser.yaml
fix failed action: https://github.com/streamnative/terraform-provider-pulsar/actions/runs/11153599950
- fix goreleaser yaml
- add CI to check goreleaser
*(or)*
*(or)*
*(example:)*
Need to update docs?
(If you need help on updating docs, create a doc issue)
(Please explain why)
(If this PR contains doc changes)
> fix: GoReleaser lint issue

- pulsar/resource_pulsar_cluster.go
- pulsar/resource_pulsar_function.go
- pulsar/resource_pulsar_namespace.go
- pulsar/resource_pulsar_namespace_test.go
- pulsar/resource_pulsar_sink.go
- pulsar/resource_pulsar_source.go
- pulsar/resource_pulsar_tenant.go
- pulsar/resource_pulsar_topic.go
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
> allow recreate resources if resources been externally removed

- .github/workflows/release.yaml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
> making terraform releaser with correct git ref

- .github/workflows/linter.yml
- .goreleaser.yaml
- pulsar/resource_pulsar_namespace.go
- pulsar/resource_pulsar_namespace_test.go
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
> fix namespace replication_clusters drift

- docs/resources/subscription.md
- pulsar/provider.go
- pulsar/resource_pulsar_subscription.go
- pulsar/resource_pulsar_subscription_test.go
Fixes https://github.com/streamnative/terraform-provider-pulsar/issues/144
*(or)*
*(or)*
*(example:)*
- …
> feat: support pulsar subscription resource

- pulsar/resource_pulsar_topic.go
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
> fix default val of publish_rate

- README.md
- docs/resources/topic.md
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
> sync docs for pulsar-topic and pulsar-subscription

- pulsar/resource_pulsar_subscription.go
- pulsar/resource_pulsar_subscription_test.go
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
> fix incorrect error message when import subscription

- .github/workflows/acctest.yaml
- Makefile
- hack/pulsar-docker.sh
- hack/pulsarimage/topicLevelPoliciesDisabled.Dockerfile
- pulsar/resource_pulsar_topic.go
- pulsar/resource_pulsar_topic_test.go
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
> fix topic policy read failed due to `Topic level policies is disabled`
